# GA Data Science 19 (DAT19) - Class 5
## Developing Mastery of Pandas, Numpy & Bokeh
####  

Justin Breucop (with parts from Craig Sakuma)

## Lab goals

- NumPy: Entering the Matrix
- Pandas: DataFrames as Bamboo
- Bokeh: Picture-Perfect Visuals

##NumPy
As we've seen in lecture, linear algebra is the branch of mathematics describing navigation between different vector spaces. This core concept is very important as a big piece of data cleansing is converting data into various formats and certain algorithms require data to be in a specific shape.

NumPy is a package designed to be used in scientific computing, and specifically around building N-dimensional array objects.

###Creating an array

In [1]:
import numpy as np
a = np.arange(25).reshape(5,5)
# arange(n) is a function that creates a 1 row array of integers of length n 
# reshape(M,N) is a method converts a list to a matrix of size MxN
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We can convert from lists to arrays. Note however unlike lists, elements of an array all have to be of the same datatype.

In [2]:
alist = [[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24]]
type(alist)

list

In [3]:
np.array(alist)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
biga = a*10
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [5]:
print biga.mean()
print biga.mean(0) #Average per column
biga.mean(1) #average per row
# type(biga.mean(1))

120.0
[ 100.  110.  120.  130.  140.]

array([  20.,   70.,  120.,  170.,  220.])

In [6]:
bigm = np.matrix(biga-20)
bigm

matrix([[-20, -10,   0,  10,  20],
        [ 30,  40,  50,  60,  70],
        [ 80,  90, 100, 110, 120],
        [130, 140, 150, 160, 170],
        [180, 190, 200, 210, 220]])

In [7]:
np.linalg.inv(biga-20)

array([[ -5.82741163e+12,  -3.82630046e+13,   6.47978853e+13,
          8.50288992e+12,  -2.92103589e+13],
       [  1.03354093e+13,   4.66192930e+13,  -6.97823380e+13,
         -4.16348403e+13,   5.44624760e+13],
       [ -6.86095256e+13,   1.33700614e+14,  -7.97512434e+13,
          3.28387473e+13,  -1.81785922e+13],
       [  1.29522470e+14,  -2.54207088e+14,   1.09657960e+14,
          2.52154667e+13,  -1.01888078e+13],
       [ -6.54209419e+13,   1.12150186e+14,  -2.49222636e+13,
         -2.49222636e+13,   3.11528295e+12]])

####Slices

In [8]:
bigm = np.array(bigm)
bigm[0]

array([-20, -10,   0,  10,  20])

In [9]:
#Same thing, but demonstrating the full slice with a colon
biga[0,:]
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [10]:
biga[:,3]

array([ 30,  80, 130, 180, 230])

Slice rules work for even more complex dimensional data

In [11]:
compa = np.arange(30).reshape(5,3,2)
compa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [12]:
# lets describe it
print compa.shape
print compa.ndim
print compa.dtype

(5L, 3L, 2L)
3
int32

In [13]:
compa[3,:,1]

array([19, 21, 23])

In [14]:
compa[0,0,0]

0

In [15]:
compa[0,0,0] = 5.9
compa[0,0,0]

5

Numpy tries to resolve conflicting datatypes, sometimes to our dismay

In [16]:
compa = compa.astype(float)
compa[0,0,0] = 5.75
compa[0,0,0]

5.75

####Random Numbers
Random numbers are very helpful and are necessary at times for testing data pipelines and running statistical analyses. Functions for creating random values are under numpy.random.

In [17]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.25109588,  0.92131942,  0.40842843,  0.88814629,  0.32451911],
       [ 0.11653304,  0.55786091,  0.58410784,  0.05161716,  0.91906662],
       [ 0.67285099,  0.05513986,  0.44958739,  0.66365954,  0.43529299],
       [ 0.01447089,  0.47676985,  0.02778103,  0.03299097,  0.40672957],
       [ 0.26250527,  0.4410875 ,  0.3376203 ,  0.52388349,  0.55998911]])

In [18]:
rm.shape

(5L, 5L)

In [19]:
print rm.mean()
print rm.mean(0) #Average per column
print rm.mean(1) #average per row

0.415322137436
[ 0.26349121  0.49043551  0.361505    0.43205949  0.52911948]
[ 0.55870182  0.44583711  0.45530615  0.19174846  0.42501714]

In [20]:
# for a different Normal Distribution, use np.random.normal
rm = np.random.normal(5,9,(30,30))
rm

array([[  2.88298417e-01,   7.29631656e+00,   1.29529969e+01,
         -9.09464383e+00,  -5.60343936e+00,   1.40103599e+01,
          1.30388358e+01,   4.45701630e+00,   5.15748288e+00,
         -4.26120497e+00,   4.01756692e+00,  -2.87836283e+01,
          1.89436681e+00,   4.32671171e+00,  -5.76308430e+00,
          2.37465293e+00,   4.84450603e+00,   5.81290092e+00,
          8.90949345e+00,  -3.80873026e+00,   1.03483334e+01,
          2.20187841e+01,   2.03814585e+01,  -3.23848345e-01,
          3.84310771e+00,   4.03170374e+00,   1.40857874e+01,
          5.15606036e+00,   6.28912418e+00,  -3.59780550e+00],
       [  1.32380272e+01,   2.53274582e+01,   1.57143618e+01,
          2.45313116e-01,   1.15765307e+01,   5.49046338e+00,
         -1.04831680e+01,   1.89751529e+00,  -2.94859531e+00,
          1.73185038e+01,   1.44339845e+01,   7.34641698e+00,
          8.68015415e+00,  -1.03252306e+01,   5.67596535e+00,
          1.12063572e+00,   2.90379481e+00,   1.19905995e+01,
          6.52900552e+00,   1.48387154e+01,  -1.17884705e+01,
          1.00045520e+01,   5.70171249e+00,   1.73251463e-01,
          6.56314688e+00,   1.41242648e+01,  -4.65560962e+00,
         -1.95073388e-01,   1.25435066e+01,   5.71074489e+00],
       [  1.40199816e+01,  -2.96060467e+00,   1.18175617e+01,
         -9.42647669e+00,   7.38749640e+00,   3.84999440e+00,
         -1.48728543e+00,   1.92672176e+01,  -3.68481769e+00,
          3.36416624e+00,   7.56343780e-01,  -4.40305223e+00,
         -3.21226954e+00,   1.16435880e+01,   3.03010455e+00,
         -4.44896853e+00,   6.11375614e+00,   1.27671388e+01,
         -4.64434002e+00,   2.68075601e-01,   7.18934764e+00,
          3.99118633e+00,   1.43921521e+00,   2.16953829e+01,
         -9.34237739e+00,  -3.09451599e+00,  -6.76080325e+00,
          9.98786996e+00,   1.17095385e+01,   1.02348516e+01],
       [  1.26650561e+01,   5.91113231e+00,   6.19981187e+00,
          2.45268796e+00,   9.09619510e+00,   3.32137763e-01,
          2.74715892e+00,  -5.27785933e+00,  -1.61509551e+00,
          1.11133987e+01,  -1.96775901e+00,   2.87301641e+00,
          1.73362004e+01,  -2.65779826e+00,   5.89296975e+00,
          1.48365383e+01,   1.67806148e+01,   1.48797751e+00,
          8.89894305e+00,  -7.79643416e+00,  -4.82498960e+00,
          4.58052507e+00,   9.93726177e+00,   1.46390546e+01,
          1.55538555e+01,   1.22204900e-01,   5.67434148e+00,
         -6.05274294e+00,   1.36925460e+01,   6.94431298e-02],
       [  6.49761972e-01,   1.84445210e+00,   2.67859602e+00,
          4.89839979e+00,   4.46787454e-01,   1.05886471e+01,
          1.06365118e+01,  -7.24766748e-01,   8.97604637e+00,
         -7.39055827e-01,  -4.77775755e+00,   4.66150433e-01,
          7.35171901e+00,   6.24243365e+00,   2.01212541e+00,
         -4.07136076e+00,   1.76459550e+01,   3.90531738e+00,
          1.02492544e+01,  -1.52485091e+00,   3.28733865e+00,
          2.41507384e+01,  -1.46361460e-01,   1.21659837e+01,
          4.78130508e+00,   1.56745400e+00,   8.57085147e+00,
          1.37015629e+01,   8.88309791e+00,   7.78398424e+00],
       [ -1.14103917e+01,   7.51012103e+00,   6.31368733e+00,
         -1.37693195e+01,   1.78276395e+01,   7.80830742e-02,
         -6.32251045e+00,   5.03068281e+00,  -1.61704810e+00,
         -6.72621066e+00,  -1.17036746e+01,   5.29908120e+00,
          1.63629471e+01,  -1.15722919e+00,  -1.22621856e+01,
          1.37762237e+01,   3.68798503e+00,  -1.23525385e+00,
         -1.90698049e+00,   8.05445568e-01,  -2.70391768e-01,
          1.32567146e+01,   1.13772820e+01,   1.05795858e+01,
          2.51209107e+01,   5.57508819e+00,   7.92246472e-01,
         -3.13359261e+00,  -1.90678993e+00,  -5.81349347e-01],
       [  1.86500717e+01,   5.72802379e+00,  -1.16413111e+01,
          1.72907759e+01,   1.14717616e+01,  -2.21385842e+00,
         -9.29424165e-01,   9.42667925e+00,  -8.88269216e+00,
         -1.52830893e+00,  -1.01104298e+01,   6.99572464e+00,
          2.51341017e+00,   9.68993727e-01,  -1.92455837e+00,
          1.10061029e+01,  -2.43974305e+00,   5.63099356e+00,
          1.11856728e+01,   1.50269575e+01,   1.12767793e+01,
          7.59220221e+00,   4.63256565e+00,   8.41640514e+00,
          1.63164385e+01,   9.77561111e+00,  -6.37236747e+00,
          1.47913414e+01,   1.28028224e+01,   9.35778118e+00],
       [  2.35918797e+01,   1.07182102e+01,   8.13334385e+00,
          6.61590042e+00,   6.84771588e+00,   4.11564902e+00,
          8.57478147e+00,   1.90490569e+01,   5.00612440e-01,
          9.51003389e+00,  -1.17974688e+01,   5.19227641e+00,
          2.97717189e+00,   3.77777102e+00,   5.78600570e+00,
         -5.99315854e+00,   6.96775047e+00,   1.37113487e+01,
          8.74284255e+00,   8.47599908e+00,   1.37946917e+01,
          3.12867490e+00,   8.56894559e-01,  -1.73361489e+01,
          1.30806876e+01,  -2.80586401e+00,  -1.39475184e+01,
          1.64009286e+00,  -9.71796606e-01,   1.11727344e+00],
       [  9.39629087e+00,   8.93190086e-01,   5.43889383e+00,
          9.54583331e+00,   1.05756272e+01,   1.01948491e+01,
          5.55783790e+00,  -9.55468371e+00,   1.15716406e+01,
          3.12678323e+01,   9.59412579e+00,   1.27326940e+00,
          1.05479540e+01,  -2.92997819e+00,   1.93635767e+00,
          1.55418919e+01,  -1.67741017e+01,   1.65551878e+01,
          2.23712128e+00,   6.26152761e+00,   8.77750273e+00,
          1.31740109e+01,   1.05304923e+01,   7.73303315e+00,
          4.03994361e+00,   1.48157663e+01,  -1.29721892e+01,
         -7.66461880e+00,  -2.05779298e+01,   5.64797472e-01],
       [  3.33192821e+00,  -1.72898261e+01,   4.89311604e-01,
          2.38748980e+01,   1.56569209e-02,  -5.67008422e+00,
          1.17392533e+00,   1.02128650e+01,   1.07115653e+01,
          4.05670845e+00,   4.59517080e+00,   3.02288972e+00,
          2.67045976e+01,   1.59432303e+01,  -2.18909533e-01,
          2.58837128e+01,   5.27069637e+00,  -1.17509093e+01,
         -3.35629356e+00,   1.65123169e+01,   5.76868648e+00,
          6.96506526e+00,   1.81011377e+00,   1.27903665e+01,
          1.29005337e+01,  -5.04357798e+00,   7.80165127e+00,
          5.31855479e+00,   6.48539157e+00,   7.43530807e+00],
       [  4.47806392e+00,  -9.62807617e+00,   9.41910693e+00,
         -5.24647935e+00,   2.10011938e+00,   5.96581111e+00,
         -1.10598805e+00,   6.48887163e+00,   1.51356385e+01,
          1.20180210e+01,   7.83774402e-01,   3.73644566e+00,
          9.95449168e+00,   3.17055756e+00,   2.40227265e+00,
          3.63543673e+00,  -6.36894824e+00,   1.39015452e-01,
         -1.06832744e-01,   2.28997490e+00,   1.08287148e+00,
         -7.57401811e+00,   2.42693824e+01,   3.48174604e+00,
          4.33352402e+00,  -2.68701869e+00,   1.01187844e+01,
          1.51161885e+01,   2.14201444e+00,   1.86469131e+01],
       [ -1.25761450e+00,  -9.04230009e+00,   1.22560865e+01,
          1.87969630e+00,   5.75161741e+00,  -8.69308578e+00,
          6.25332662e+00,   5.40076976e+00,   1.02573115e+01,
          1.00212490e+01,   1.08151454e+01,   2.53453929e+00,
         -1.35056743e+01,   1.48397038e+01,  -5.08113327e+00,
         -1.95217597e-01,  -4.05954380e+00,  -4.19390405e+00,
          1.02896570e+01,   4.54431101e+00,   3.45068293e+00,
          4.02603923e+00,  -3.25742233e+00,   1.43581197e+01,
          1.46617493e+01,  -8.63539619e-02,   1.70256242e+00,
          6.02841250e+00,  -1.65211547e+00,   6.24278825e+00],
       [ -4.54396759e+00,   4.41384605e+00,  -1.10757722e+01,
          1.05022746e+01,   3.78706159e+00,  -2.16714074e+01,
          9.77270903e+00,   8.29916060e+00,  -1.73348275e+01,
         -1.60136171e+00,  -2.42734837e+00,   1.43686261e+01,
          1.06452937e+01,   8.89734340e+00,  -1.30203970e+01,
          1.90530581e+01,   6.57834775e+00,   2.64111126e+00,
          1.56769528e+00,   7.61013382e+00,   5.60917073e+00,
          8.72200861e+00,  -4.58183660e-01,   4.72640978e+00,
          2.37580591e+00,   1.46475631e+01,  -1.21360834e+00,
          7.15672880e+00,   2.64009169e+00,   1.17198586e+01],
       [  2.43303553e+01,   6.91910283e+00,  -1.85204648e+01,
         -2.07811189e+00,   1.33688155e+01,   3.16466232e+00,
          1.06395041e+01,  -2.65752030e+00,  -2.18496329e+00,
          5.67831271e+00,   1.74973331e+01,   4.33912887e+00,
         -5.12394738e+00,   5.01194740e+00,  -3.95042586e+00,
          3.56982174e+01,  -1.28272150e+01,   3.16830567e+00,
          1.12441740e+00,   9.86267442e+00,  -1.26287071e+01,
          1.63845972e+01,   4.76843134e+00,  -6.53833671e+00,
          8.37674099e+00,   2.57104915e+00,   1.76457638e+01,
          2.91485551e+01,   6.10011392e+00,   1.78707235e+00],
       [  6.15378522e+00,   3.47443378e+00,   1.61292755e+01,
          2.18162257e+01,   8.14554124e+00,   5.08324796e+00,
          4.59508245e+00,   1.62344748e+01,  -4.93754147e+00,
          1.00994635e+01,   1.12163313e+01,   3.53433019e+00,
         -2.34987643e+00,  -1.43595224e+01,   6.00190508e+00,
          3.38559396e+00,  -1.57061470e+00,   1.12246268e+01,
          2.21149216e+01,   1.32323779e+01,   4.96822310e-01,
          1.25044016e+01,   6.47722265e-01,   1.30814567e+01,
          5.00385538e+00,   1.87770177e+01,  -1.11241834e+01,
         -1.17433952e+00,   9.81235498e+00,   5.95227312e+00],
       [  3.61952559e+00,   8.97437322e+00,  -1.01614961e+01,
          4.17361641e-01,   7.41509527e+00,   3.83845924e+00,
          1.36842058e+01,  -2.59657937e-01,   9.75443756e+00,
          2.21464043e+01,   1.90565954e+01,   3.02176845e+00,
          3.45267130e+00,   5.31156990e+00,   1.91073543e+01,
          3.46421232e+00,   3.86740032e+00,   2.69291715e+01,
         -1.08917156e+00,   9.66965741e+00,  -5.00888934e+00,
         -1.40845515e+01,   4.96222502e+00,  -1.46507213e+01,
         -1.52919313e+01,   1.40076855e+00,   5.46606559e+00,
          4.39417509e+00,   1.97993027e+01,  -1.02535731e+01],
       [ -4.31353185e+00,   8.92047354e+00,   1.00336604e+01,
          1.09794574e+01,  -1.03636504e+01,   1.32252618e-01,
          3.97880227e-01,  -2.28594555e+00,   1.64043291e+00,
          1.98129836e+01,   5.56639926e+00,   7.79336126e+00,
         -7.57317302e+00,   1.94001265e+01,   7.89099205e-01,
          1.51524837e-01,   1.03803390e+01,   1.40400070e+00,
          1.26259410e+01,  -6.46791590e+00,   5.35109579e+00,
          9.71019678e+00,   1.19608199e+01,  -3.66800441e+00,
          5.67933542e+00,  -8.27030974e+00,  -7.64397651e+00,
         -3.55569063e+00,   6.71488469e+00,   1.04975666e+01],
       [ -1.15214891e+01,   3.22271268e+00,   4.55957210e+00,
          1.42108831e+01,   1.25525752e+01,  -5.56464686e-01,
          2.36098379e+00,   1.67987785e+00,  -2.23167523e+01,
         -7.25902889e+00,   6.28204042e+00,   8.43391213e+00,
          1.28509430e+01,  -2.62224333e+00,   2.52967184e+00,
          7.96369218e+00,   1.03361890e+01,   5.00803383e+00,
         -7.14398309e+00,   1.13903199e+01,  -3.05319183e+00,
          2.83600693e+00,   1.21857679e+01,   3.99791251e+00,
          2.14055946e+01,  -3.87516298e+00,  -8.99482817e-01,
          9.14521019e+00,   1.02343808e+01,   1.66014644e+01],
       [  1.43383931e+01,  -8.30162641e-02,   3.27221869e+00,
          3.64198434e+00,   7.03111053e-01,   1.07023642e+01,
          6.03094271e+00,   2.90443493e+00,  -1.18462134e+01,
         -1.57578448e+00,  -3.56665508e+00,   1.70600873e+01,
          5.69608308e+00,   1.15939492e+01,   5.10433558e+00,
         -6.80909920e-02,   1.75862194e+01,   1.53107180e-01,
         -5.84568009e+00,   7.17303253e+00,   1.86774486e+01,
          8.03195418e+00,  -8.45618705e-01,   1.09205285e+01,
          1.66222474e+01,   8.98552257e+00,   2.74820014e+00,
          8.25197059e+00,   4.74128601e+00,   5.92052890e+00],
       [ -1.23694208e+01,   5.06923689e+00,   1.99158147e-01,
          1.03312338e+01,   1.68369625e+01,   2.99511747e+00,
         -8.11819715e+00,  -1.54911389e+00,  -1.24676087e+01,
          5.99472053e+00,   8.82398034e+00,   2.77166043e+01,
          9.46999378e+00,   7.84990468e+00,   6.28432987e+00,
          2.64596605e+00,  -1.11724598e+01,  -4.51203358e+00,
          2.05856177e+01,   3.53784523e+00,  -3.76569198e+00,
          1.01137543e+01,  -6.85334628e+00,   4.24726596e+00,
          7.81457200e+00,   1.57395775e+01,  -1.06623945e+01,
          1.44934169e+01,   7.56555344e-01,   3.47759659e+00],
       [ -1.03929965e+01,   1.26314020e+01,   8.88339294e-01,
          1.67698954e-02,  -4.58635177e+00,  -9.09744577e+00,
          1.02511236e+01,   9.25890908e+00,  -5.27808963e-01,
          2.13144686e+01,   1.19736225e+01,   7.99835429e+00,
          2.29664398e+01,  -2.90240255e+00,   3.32745250e+00,
         -2.51196246e+00,   1.67717221e+01,   1.50190560e+00,
         -5.21581718e+00,   1.53667262e+01,  -7.55592368e+00,
         -5.66751225e+00,   3.97364508e+00,   9.63450814e+00,
         -1.67008183e+00,   1.08087676e+01,  -7.04579485e+00,
         -7.51087221e-01,   5.92699433e+00,   1.15510111e+01],
       [  8.42926019e+00,   9.37046377e+00,  -1.81370100e+00,
         -4.13601192e+00,   1.55611499e+00,   1.71200027e+01,
          6.28536124e+00,   4.16904698e+00,   3.10671027e+00,
          1.71446422e+01,   4.32822324e+00,   7.70809899e-01,
          2.16158950e+00,   6.24841451e+00,  -2.81261404e+00,
         -6.25653301e+00,   2.68297766e+00,  -1.82206876e-01,
          1.98265992e+00,   1.40858602e+01,   1.09727376e+01,
         -2.25646812e+00,   2.88355875e+00,   1.85128327e+01,
         -1.38694693e+01,   5.24813414e+00,  -4.69762305e+00,
         -3.95209099e+00,   1.23397318e+01,   3.01533954e+01],
       [  3.78991868e+00,   5.70855698e+00,  -1.21783187e+00,
          2.30398838e-01,  -5.51771786e+00,   2.00964112e+01,
         -1.16850258e+01,   1.18639783e+01,   8.09307528e+00,
         -3.32309621e+00,   1.77600396e+00,   4.38794396e+00,
          1.65456231e+01,   1.30946373e+01,   4.99003578e+00,
          1.91203473e+01,   1.44703937e+01,   3.03989104e+00,
          3.55292243e+00,   1.96712183e+01,   1.48388213e+01,
         -3.97332009e+00,   1.74050150e+01,   1.15172588e+01,
          2.15480028e+01,  -8.07200850e+00,   1.85917559e+01,
          5.46804816e+00,   2.33877163e+00,   6.86801636e+00],
       [  4.61456226e+00,  -1.66383988e-01,   6.51737976e+00,
          5.46646674e-01,   2.44422006e+00,   1.63204644e+01,
         -1.45306174e+01,   6.62032308e+00,   6.64221920e+00,
         -1.63217943e+01,   1.75560521e+01,  -5.96973767e-01,
          9.63990117e+00,   2.62445189e-01,  -2.34945296e+00,
         -6.51157084e+00,  -6.39358839e+00,   1.25635137e+01,
          7.16522907e+00,  -1.17061206e+00,   4.20285663e+00,
          3.08257465e+00,   1.22194603e+01,   9.80951876e+00,
          6.55776802e+00,  -5.11573450e+00,   9.11517479e+00,
          1.58450936e+01,   1.24159708e+01,  -1.36618813e+01],
       [  1.76659505e+01,  -2.98213350e+00,   1.29594919e+01,
          8.63894024e+00,   2.49349182e+01,   1.23655321e+00,
          1.20392402e+01,   4.98867133e+00,  -6.64616849e+00,
          1.19440494e+01,   1.02660610e+01,   5.49698021e+00,
         -4.81844680e+00,   8.98316196e+00,   1.08927245e+01,
         -2.88140412e+00,   5.30315499e+00,  -4.13897388e+00,
         -3.83309723e+00,  -9.80514104e-01,   2.25906852e+01,
          2.30999839e+01,   7.82293832e+00,   1.51334531e+01,
         -2.76764142e+00,   2.32029347e+00,   9.76772730e+00,
          3.00369424e+00,  -3.29396546e+00,   1.48303620e+01],
       [  1.01580004e+01,  -5.96473798e+00,   6.08363752e+00,
          8.59331312e+00,   6.84929728e+00,   2.25832620e+01,
          1.38962304e+01,   5.77966496e+00,   2.06127660e+00,
         -7.06837750e+00,   4.86434098e+00,   1.15560165e+01,
          1.04493962e+01,  -4.70705724e+00,   1.10666861e+01,
         -1.06350403e-01,   9.39338831e+00,   7.86110612e+00,
          3.98952608e+00,   2.89672788e+00,   1.17552210e+01,
          1.88631980e+00,  -7.81945205e+00,  -3.83186024e-02,
          1.14213795e+01,   6.28320690e+00,   3.38807838e+00,
          1.47836076e+01,   1.96064044e+01,  -8.19557893e+00],
       [  1.27748816e+01,   1.18196008e+01,   6.24335082e+00,
         -9.55253809e+00,   7.26232646e+00,   4.72073477e+00,
         -1.00076120e+00,   5.11028918e+00,   1.33278077e+01,
          7.66246251e+00,   8.06773326e+00,   1.52748143e+01,
          2.21821271e+01,   8.27656427e-01,   4.43833179e+00,
          1.13093975e+01,   7.06359412e-01,  -6.07648086e+00,
          1.01430319e+01,  -8.95527424e-01,   2.61315936e+01,
          7.06362088e+00,   1.86662230e+01,  -5.72945891e+00,
          1.44293746e+01,   6.67459991e+00,   1.27691339e+01,
          1.69001634e+01,   6.02849723e+00,   4.97070618e+00],
       [  1.02570527e+01,   3.29866209e+00,   2.29039879e+01,
         -2.19338270e+00,   8.39028512e+00,   1.43453453e+00,
          9.68682110e+00,   6.77626857e+00,   5.10040330e+00,
          1.32874002e+01,   1.67844635e+01,  -4.70987005e-01,
          6.76303662e-01,   1.75449401e+01,  -2.00381310e+00,
          1.32025166e+00,  -1.77331731e+00,  -8.65963913e+00,
          1.17727777e+01,   2.12731279e+00,  -7.81194590e+00,
          7.27350061e-01,  -9.63169793e+00,   3.15722371e+00,
          3.72415022e+00,   1.13085909e+00,   3.42858384e+00,
         -6.48922452e+00,   5.69329575e+00,   4.74885013e+00],
       [ -8.49644457e+00,   7.68206956e+00,  -2.90899264e+00,
          4.90257266e+00,  -7.57437409e+00,   8.91087751e+00,
         -6.25303244e+00,  -5.41511582e+00,   1.88492933e+00,
          7.29523848e+00,   1.26605725e+01,  -1.75880769e+00,
          4.60736436e+00,   1.71768044e+01,   9.61060015e+00,
          8.81022795e+00,   1.80312281e+01,  -1.85790585e+00,
          1.19182255e+01,   1.42411377e+01,   1.68827051e+01,
          1.94339798e+01,  -1.29119582e+01,  -2.39431203e+00,
          2.01238133e+01,   1.37158276e+01,   3.63666226e+00,
         -7.74001465e+00,  -6.94778289e-01,   4.62379623e+00],
       [  5.79180003e+00,   9.06109827e-01,   6.04699527e+00,
         -6.22188380e+00,   8.26709113e+00,   3.00105736e+00,
         -7.78488140e+00,   1.38540778e+01,   9.53669619e+00,
         -6.25608844e-01,   1.96006289e+01,  -4.83844028e+00,
          1.07752012e+01,   4.67224648e+00,   6.35154475e+00,
         -1.08998509e+01,   1.26303258e+01,   4.42239458e+00,
          1.58160368e+01,   3.25347288e+00,   7.05501598e+00,
         -1.06349320e+00,   8.15394705e+00,  -2.95013789e-01,
          1.15906221e+01,  -5.03643058e+00,   1.61378898e+01,
          1.58276993e+01,   3.38234452e+00,  -1.14213518e+01]])

In [21]:
print rm.mean(), "which is hopefully close to the input mean"
print rm.var(), "which variance = stdev squared"
print np.median(rm)

4.76701127895 which is hopefully close to the input mean
77.7149436892 which variance = stdev squared
4.77486820771

Find more distributions and random functions here: http://docs.scipy.org/doc/numpy/reference/routines.random.html

###Exercise 1
1) Create a 4x5 array of integers numbering 0 to 19.

In [22]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

2) Create a 50x500 array with a mean of 20 and variance of 100. Save it to a variable called  `biggie`

In [23]:
biggie = np.random.normal(20,10,(50,500))
print biggie.shape
print biggie.mean()
print biggie.var()

(50L, 500L)
19.991084069
101.06996582

3) Change the mean of the array to a value within 1 of 0 and the variance within 1 of 25. Think about what the mean and the variance represent and try using various mathematical operations.

In [24]:
morph = (biggie - 20)/2
print morph.mean()
print morph.var()

-0.00445796549195
25.267491455

##Pandas: DataFrames as Bamboo
You've already been exposed to dataframes in the previous labs so lets get into dataframes and how we can work with them.

In [25]:
import pandas as pd

data = pd.read_csv("../data/titanic.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [26]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
data[data.Age>65]

In [ ]:
data[(data.Age==11)&(data.SibSp==5)]

In [ ]:
data[(data.Age==11)|(data.SibSp==5)]

###Cleaning Data

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB

####Working with nulls
Exclude data

In [ ]:
# data[data.Age.isnull()]
data[data.Age.notnull()]

In [ ]:
# You can also just replace the nulls
data.Age[data.Age.isnull()].fillna(0)

In [ ]:
#Replace with the mean to preserve statistical values
avg_age = data.Age[data.Age.notnull()].mean()
print avg_age
data.Age.fillna(avg_age)

####Replace with random normal distribution

In [ ]:
# Get values of mean and standard deviation
data.Age[data.Age.notnull()].describe()

In [ ]:
# Replace null values with 
data.Age.fillna(np.random.normal(29.7,14.5),inplace=True)

In [ ]:
data.Age.fillna(np.random.normal(29.7,14.5)).describe()

###Convert categorical data to numerical

In [ ]:
data.Sex=='female'

In [ ]:
data.rename(columns={'Sex':'Is Female'},inplace=True)
data['Is Female']=data['Is Female']=='female'
data.head()

In [ ]:
# get unique values of Embarked
data.Embarked.unique()

In [ ]:
# replace values with numbers
data.Embarked.replace(['S', 'C', 'Q'],[1,2,3],inplace=True)
data.head()

###Selecting with .loc, .iloc, & .ix

Selecting data in pandas can be tricky. The main takeaway is that .loc looks for index labels, .iloc looks for the integer index position, and .ix can be a mix.

In [ ]:
df = pd.DataFrame(np.random.randn(6,4),index=list('abcdef'),columns=list('ABCD'))
df

In [ ]:
df.loc['f']

In [ ]:
df.iloc[len(df.index)-1]

In [ ]:
df.A.ix['f'] == df.A.ix[-1]

In [ ]:
cc = list('cookies')
cc[-4]

###Group by

In [ ]:
# Find average age of passengers that survived vs. died
data.groupby('Survived')['Age'].mean()

In [ ]:
# Count number of female passengers
data.groupby('Is Female')['PassengerId'].count()

In [ ]:
data.groupby(['Survived','Pclass'])['PassengerId'].count()

###Apply

In [ ]:


# Convert ticket prices to USD
data.Fare.apply(lambda x: x*1.6)

In [ ]:
data.Name

In [ ]:
data.Name.apply(lambda x: x.split(",")[0])

###Concatenate

In [ ]:
data_first_half = data.iloc[0:10,:]
data_first_half.info()

In [ ]:
data_second_half = data.iloc[10:,:]

remake_data = pd.concat([data_first_half,data_second_half])
remake_data.info()

###EXERCISE 2
1) Replace Pclass numbers with 'First Class', 'Second Class', 'Third Class'

2) What was the average ticket price for survivors vs. dead passengers?

###Bonus!!!
Round all ages to the nearest year using `apply`

##Bokeh: Picture Perfect Visuals

To install Bokeh, go to a terminal and type:

`conda install bokeh` 

Bokeh is built by the same people that created Anaconda (Continuum Analytics) and is designed out of the box for web display, making it nice for creating presentation ready, interactive visuals quickly. Labs in this course will be shown in Bokeh. Checkout http://bokeh.pydata.org/en/latest/docs/quickstart.html#concepts to see some of the range of capabilities.

In [ ]:
from bokeh.plotting import figure, output_notebook,show,vplot
output_notebook()

In [ ]:
import pandas.io.data
import datetime
aapl = pd.io.data.get_data_yahoo('FB', 
                                 start=datetime.datetime(2015, 4, 1), 
                                 end=datetime.datetime(2015, 4, 28))

In [ ]:
# prepare some data
x = aapl.Low
y = aapl.High

# create a new plot with a title and axis labels
p = figure(title="Stock High vs. Low", x_axis_label='Low', y_axis_label='High')

# These are glyphs
p.circle(x, y,size=30,alpha=.5,)
p.line(x,x*y.mean()/x.mean())

# show the results
show(p)

At its core, Bokeh is built up with Plots and Glyphs. Plots are created with the figure keyword and then glyphs are visuals that are added to the visualization. The visuals are scalable, interactive and savable. You can even create vectorized colors.

In [ ]:
# prepare some data
N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = ["#%02x%02x%02x" % (r, g, 150) for r, g in zip(np.floor(50+2*x), np.floor(30+2*y))]

TOOLS="resize,crosshair,pan,wheel_zoom,box_zoom,reset,box_select,lasso_select"

# create a new plot with the tools above, and explicit ranges
p = figure(tools=TOOLS, x_range=(0,100), y_range=(0,100))

# add a circle renderer with vecorized colors and sizes
p.circle(x,y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)

# show the results
show(p)

In [ ]:
p1 = figure(title="Titanic Ages Dead",x_axis_label = 'Age',y_axis_label = 'Count')
#construct the histogram
hist, edges = np.histogram(data.Age[data.Survived==0].values, density=True, bins=50)
#Construct your x axis
x = np.linspace(data.Age.min(),data.Age.max(),100)
#add the bars, scaling the value to the full count of people
p1.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')

p2 = figure(title="Titanic Ages Survived",x_axis_label = 'Age',y_axis_label = 'Count')

hist, edges = np.histogram(data.Age[data.Survived==1].values, density=True, bins=50)
x = np.linspace(data.Age.min(),data.Age.max(),100)
p2.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')


show(vplot(p1,p2))